package org.bstraining.model;

/** 仿真器事件类型。遥测(TELEMETRY)与口令完成(COMMAND_COMPLETE)以外均为系统响应事件。 */
public enum EventType {
    COMMAND_ACCEPTED,
    COMMAND_COMPLETE,
    COMMAND_REJECTED,
    GEN_STARTED,
    GEN_START_FAILED,
    GEN_OUTPUT_CHANGED,
    BUS_ENERGIZED,
    BUS_DEENERGIZED,
    LINE_CLOSED,
    LINE_OPENED,
    LINE_TRIP_FAULT,
    LOAD_RESTORED,
    LOAD_DISCONNECTED,
    UNDERFREQ_SHED,
    SYNC_CHECK_PASSED,
    SYNC_CHECK_FAILED,
    ISLAND_MERGED,
    MISPARALLEL_TRIP,
    TELEMETRY
}
